SELECT TOP (1000) [PolicyNumber]
      ,[CustomerID]
      ,[Gender]
      ,[Age]
      ,[PolicyType]
      ,[PolicyStartDate]
      ,[PolicyEndDate]
      ,[PremiumAmount]
      ,[CoverageAmount]
      ,[ClaimNumber]
      ,[ClaimDate]
      ,[ClaimAmount]
      ,[ClaimStatus]
  FROM [Insurancedb].[dbo].[InsuranceData]

  select * from [dbo].[InsuranceData]
